### ISSUE TITLE
Switch to a better theme

### ISSUE THREAD

**Issue by monsieurhannes** [monsieurhannes/repaircafe#6]
I found this forty-theme, but you might have another idea for our homepage.
Would be great to have one of them developed to a stage where it just works :P

**Comment by monsieurhannes** [comment]
The official homepage gives some advice how to use the theme. Could it be that we don't have all the theme information? There is a specific section for netlify.
https://themes.gohugo.io/forty/

**Comment by qerub** [comment]
That page is for the Hugo theme, not the Jenkins theme.

**Comment by monsieurhannes** [comment]
Good point:
https://github.com/andrewbanchich/forty-jekyll-theme

**Comment by monsieurhannes** [comment]
Wouldn't it help to copy all the original layout files as well? Basically the whole repository?

**Comment by qerub** [comment]
I assume it's necessary if we want to change the page layout. I was hoping we could do with the default (but I didn't check whether it would be enough for us).

**Comment by monsieurhannes** [comment]
Ok, now comes your time to shine, I guess there is a way to copy the original repository to our repository, without saving over our files?

**Comment by qerub** [comment]
Changing issue to "Switch to a better theme" after verbal discussion. 🙂
