### ISSUE TITLE
I can't merge qerub's pull request...

### ISSUE THREAD

**Issue by monsieurhannes** [monsieurhannes/repaircafe#8]
I'm trying to merge [forty](https://github.com/monsieurhannes/repaircafe/pull/4) to `master`, but somehow there is a conflict with `_config.yml`. Is there a way to resolve the conflict? When I try to do that I get this image:

![grafik](https://user-images.githubusercontent.com/20651440/58831511-26055c00-864d-11e9-8950-4428c578f128.png)

**Comment by qerub** [comment]
The conflict was due to `_config.yml` was being changed on both branch `master` and `forty`. GitHub's merge conflict view took forever to load but it actually showed to me. I resolved the conflict by reverting the changes made on `master` (commit c73ce238d5aac8c9726f7200d6c4f9a1b93d4b24).

**Comment by monsieurhannes** [comment]
I see... I thought it's a browser extension and loaded it on 3 different browsers. But considering that it would actually take forever didn't come to my mind. Tack!
